# Site settings
baseurl = "http://明奇.top/"
#languageCode = "en-us"
title = "心有玲曦遇见你"
theme = "LoveIt"
# [en, zh-cn, fr, pl, ...] determines default content language
# [en, zh-cn, fr, pl, ...] 设置默认的语言
defaultContentLanguage = "zh-cn"
# Header config
# 页面头部导航栏配置
[params.header]
# desktop header mode ("fixed", "normal", "auto")
# 桌面端导航栏模式 ("fixed", "normal", "auto")
desktopMode = "fixed"
# mobile header mode ("fixed", "normal", "auto")
# 移动端导航栏模式 ("fixed", "normal", "auto")
mobileMode = "auto"
# Header title config
# 页面头部导航栏标题配置
[params.header.title]
# URL of the LOGO
# LOGO 的 URL
logo = ""
# title name
# 标题名称
name = "心有玲曦遇见你"
# you can add extra information before the name (HTML format is supported), such as icons
# 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
pre = "<i class='far fa-kiss-wink-heart fa-fw'></i>"
# you can add extra information after the name (HTML format is supported), such as icons
# 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
post = ""
# whether to use typeit animation for title name
# 是否为标题显示打字机动画
typeit = true

# 每页显示的文章数量用于分页
paginate = 20
# Author config
# 作者配置
[author]
name = "李明奇"
email = "lidefu_420@163.com"
link = ""


# Footer config
# 页面底部信息配置
[params.footer]
enable = true
# Custom content (HTML format is supported)
# 自定义内容 (支持 HTML 格式)
custom = ''
# whether to show Hugo and theme info
# 是否显示 Hugo 和主题信息
hugo = false
# whether to show copyright info
# 是否显示版权信息
copyright = true
# whether to show the author
# 是否显示作者
author = true
# site creation time
# 网站创立年份
since = 2020
# ICP info only in China (HTML format is supported)
# ICP 备案信息，仅在中国使用 (支持 HTML 格式)
icp = '<div style="width:400px;margin:0 auto; padding:20px 0;"><a target="_blank" href="http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=11011402012187" style="color:#666" target="_blank" ><img src="https://limingqi.oss-cn-beijing.aliyuncs.com/mingqi_blog/img/beian.png" style="float:left;"/>京公网安备 11011402012187号</a>&nbsp;&nbsp;&nbsp;&nbsp; <a style="color:#666" target="_blank" rel="noopener" href="http://beian.miit.gov.cn/">京ICP备2021039774号</a></div>'
# license info (HTML format is supported)
# 许可协议信息 (支持 HTML 格式)
#license= '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

# 主页信息设置
[languages.zh-cn.params.home]
# RSS 文章数目
rss = 10
# 主页个人信息
[languages.zh-cn.params.home.profile]
enable = true
# Gravatar 邮箱，用于优先在主页显示的头像
gravatarEmail = "lidefu_420@163.com"
# 主页显示头像的 URL
avatarURL = "config.toml"
# 主页显示的网站标题 (支持 HTML 格式)
title = "心有玲曦遇见你"
# 主页显示的网站副标题
subtitle = "关于云技术 操作系统 编程的学习心得"
# 是否为副标题显示打字机动画
typeit = true
# 是否显示社交账号
social = false